### ISSUE TITLE
Dados Geoses

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#1]
# Descrição

Essa tarefa tem como principal função debater sobre os dados e criar um canal único de compartilhamento

**Comment by LeoSilvaGomes** [comment]
https://docs.google.com/spreadsheets/d/11lqLMV3h_uuNaVNOFMFkb4n7GEuY6SOupS3Qc3LzcBE/edit#gid=986751995

Esse planilha apresentará a coleta inicial dos dados relacionados aos municipios, tendo até o momento 14 principais dados a serem incluidos no atlas

**Comment by Alinaflores** [comment]
## Description
Below we detail about GeoSES dataset for development team.

## Link

https://www.dropbox.com/s/j0y5wsi896joib0/GeoSES_BR.xlsx?dl=0

## Details

| Name | Description | Descrição | Label | Rótulo | Format | Classification |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: |
|     |     |     |     |     |    |    |
|     |     |     |     |     |    |    |
|     |     |     |     |     |    |    |








## Coments

**Comment by Alinaflores** [comment]
We observed 5 missing cities from the dataset. 
![missings dados](https://user-images.githubusercontent.com/54119740/164297933-3a61db2b-fb19-4e17-92ae-5169813038ce.png)
