### ISSUE TITLE
Population and vehicle fleet data (Mobilidados)

### ISSUE THREAD

**Issue by Alinaflores** [gpmc-lab-ufrgs/atlas#10]
## Description
I want to include **population data** and **vehicle fleet data** that was collected in the Mobilidados.

## Link

[https://docs.google.com/spreadsheets/d/1Ky_kBzxwPdY1NSzjQWi27iXw9DVaOJzk6oYxnCtKOUE/edit#gid=0]()

## Details

| Name | Description | Descrição | Label | Rótulo | Format | Classification |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: |
|Pop_2020|Population by municipality (year 2020)|População por município (ano 2020)|Population|População|Float|Demográfica (D)|
|Frota_2020|Fleet of cars, vans, vans, motorcycles, scooters and SUVs in the year 2020|Frota de automóveis, caminhonetes, camionetas, motocicletas, motonetas e utilitários no ano 2020|Vehicles fleet|Frota de veículos|Float|Demográfica (D)|

## Comments
The spreadsheet I shared has 4 columns: "CD_MUN", "MUNICIPIO", "Pop_2020"' and "Frota_2020". So, there are 2 columns with geographic location (city code and city name) and 2 columns with data (population and vehicle fleet).

**Comment by LeoSilvaGomes** [comment]
should Frota_2020 be a demographic data? I think this can be analysed to have new topic or in a subtopic about it!

**Comment by Alinaflores** [comment]
About this submission, please, ignore the column "Pop_2020".
Consider only the vehicle fleet data, column name "Frota_2020".
We can discuss if demographic is the better classification for "Frota_2020". Maybe it can be classified in a consumption or possession dimension.

**Comment by Alinaflores** [comment]
Link to the dataset at Dropbox folder: https://www.dropbox.com/s/mo50k0zto9ih2kd/Mobilidados.xlsx?dl=0
