### ISSUE TITLE
Create description about research grant

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#11]
## Description
A detailed description about the grant and what is the requirement we need for the project 

## Example
![image](https://user-images.githubusercontent.com/61520601/146378164-c72ed689-50b3-43ad-ab3f-c6779ad3d3ab.png)

**Comment by LeoSilvaGomes** [comment]
Atlas Opportunity é um projeto herdado de uma pesquisa com aplicabilidade no Sul da Austrália conduzida pelo MIT (Massachusetts Institute of Technology), a mesma revela as relações entre a mobilidade urbana e a economia (https://opportunity.mit.edu/). Por isso tem sido criado uma aplicação com foco na na amostragem da pesquisa, mas voltado para proprietários de pequenas empresas, auxiliando a escolha de melhores locais para determinados comércios, e planejamento público, servindo de base para criação de políticas públicas com foco em mudanças socioculturais. Desta forma, o Brazil Atlas Opportunity se espelha nos objetivos herdados e propõem a criação de uma plataforma que possa agregar insumos para futuros empresários e desenvolvimento cultural, tecnológico e turístico. Sabendo disso, estamos à procura de uma pessoa que goste de desafios, possa aprender juntamente com o projeto e consiga se ver essencialmente no projeto. Perfil desejado: Inglês fluente (para leitura e escrita), Conhecimento em JavaScript, HTML e CSS e Interesse em aprender React, Typescript.

**Comment by gpmc-ufrgs** [comment]
O Atlas de Oportunidades (https://opportunity.mit.edu/) está sendo desenvolvido numa rede internacional com o MIT (Massachusetts Institute of Technology) e outras 4 universidades estrangeiras e 4 brasileiras. Nosso objetivo é criar um portal que auxilie as pessoas e organizações que queiram empreender, gerar emprego e renda, e que não tenham conhecimento técnico para identificar oportunidades de negócio.
Precisamos de um desenvolvedor para ajudar no projeto. Perfil desejado: inglês fluente (para leitura e escrita), conhecimento em JavaScript, HTML e CSS e interesse em aprender React, Typescript e Git.
Interessados favor mandar CV para brei@ufrgs.br. 
A bolsa é de Apoio Técnico do CNPq, podendo ser de R$ 550 ou R$ 400, dependendo do perfil da pessoa. Mais informações sobre o perfil do bolsista de apoio técnico: https://files.cercomp.ufg.br/weby/up/85/o/RN-017-2006.pdf . Horário flexível.
