### ISSUE TITLE
Spike/Bug - Identify the error on the CI

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#119]

**Comment by DouglasMonteles** [comment]
Aparentemente o CI está acusando erro na etapa de executar o linter: `yarn lint`, em específico, ele está informando dois erros que estão acontecendo:

1. 'module' is not defined (alias.js)
2. Definition for rule 'import/no-extraneous-dependencies' was not found

No primeiro erro, é necessário informar ao lint que ele precisa considerar a variável global `module`, com esta definição podendo ser feira no arquivo `.eslintrc.json`

Este segundo ocorre devido ao fato do arquivo `.eslintrc.json` especificar na linha 51 o seguinte comando `"import/no-extraneous-dependencies": ["error", { "devDependencies": true }],`. Isso habilita o lint a considerar como erro qualquer tentativa de exportação de módulos, seja com o `module.exports`, `export default`, etc. Como a exportação de módulos é uma das vantagens de se utilizar o ReactJS, e neste projeto, é utilizada em mais de 100 arquivos, acredito que a melhor alternativa seja desabilitar esta opção.
