### ISSUE TITLE
Create error state component

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#120]
## Description

With the connection with the atlas API, we need to make the user experience enjoyable, so should be necessary to create a error state component as a fallback screen when the API error.

### Expectation

- Create a modal or screen showing a generic error
   - `screen == modal` - the map should be showing in the background

## Warning

The atlas API is not connected yet with the front, instead to wait for this moment, was decided to develop the component to complement that behavior when it would be ready.

## Checklist

- [x] Propose a screen error, commented on this task (figma example)
- [x] Approved proposed screen 
- [x] Create the error state component
- [x] Create PR about the task

**Comment by CibeleG** [comment]
@LeoSilvaGomes @AnaBeatrizPontes Antonio and I have created some versions in figma of the error component. Can you guys take a look? [Error component figma](https://www.figma.com/file/xNCHBCWhgjZtJt1r2bAkw8/Error-State-Component?node-id=0%3A1&t=yDDc7Dbax3ENBuKh-0)

**Comment by LeoSilvaGomes** [comment]
I think the component can be smaller and centralized! I loved the ideia, but what do you think to create reload button in this alert component? 

Please give some references and a lib to use in the development!

**Comment by AnaBeatrizPontes** [comment]
I agree with @LeoSilvaGomes about the component be a little smaller and centralized, I really liked the idea though. The component is really good and compatible with Atlas. A reload button will suit good in this component to.

**Comment by AntonioIgorCarvalho** [comment]
@LeoSilvaGomes @AnaBeatrizPontes thanks for the feedback! Here is an [updated version](https://www.figma.com/file/xNCHBCWhgjZtJt1r2bAkw8/Error-State-Component?node-id=0%3A1&t=irOBr3Xt72wyWSF7-0), with 3 different designs. We are using the [Material UI library](https://mui.com/material-ui/react-alert/) for reference.

**Comment by AnaBeatrizPontes** [comment]
I liked the second version, centralized and smaller. The reload button looks nice too.

**Comment by LeoSilvaGomes** [comment]
I would suggestion just to make the icon smaller, otherwise it is perfect
