### ISSUE TITLE
Create loading state component

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#121]
## Description

With the connection with the atlas API, we need to make the user experience enjoyable, so should be necessary to create a loading state component as a fallback screen when the API is loading.

### Expectation

- Create a modal showing a generic loading
   - the map should be showing in the background
   - should show feedback loading animation

## Warning

The atlas API is not connected yet with the front, instead to wait for this moment, was decided to develop the component to complement that behavior when it would be ready.

## Checklist

- [ ] Propose a screen loading, commented on this task (figma example)
- [ ] Approved proposed screen 
- [ ] Create the loading state component
- [ ] Create PR about the task

**Comment by LucasGlopes** [comment]
@LeoSilvaGomes , I made this example in Figma for the [Loading Component](https://www.figma.com/file/btzYmKVvdFS59xTDfCaRZ1/Loading-Component?node-id=0%3A1&t=5Irvs5Qcxp17qheD-1).
Could you give it a look?

**Comment by LeoSilvaGomes** [comment]
> @LeoSilvaGomes , I made this example in Figma for the [Loading Component](https://www.figma.com/file/btzYmKVvdFS59xTDfCaRZ1/Loading-Component?node-id=0%3A1&t=5Irvs5Qcxp17qheD-1). Could you give it a look?

I think we can go with a more simple component 
- smaller
- with white theme (the base of our modals and side bar is white)

I really think, isn't necessary the word loading too :D @AnaBeatrizPontes  give your opinion here please.

Please, add your reference in the comment too, I think it's always good to see your way to think.

**Comment by LucasGlopes** [comment]
@LeoSilvaGomes ,thanks for the feedback. Here's the updated [version](https://www.figma.com/file/btzYmKVvdFS59xTDfCaRZ1/Loading-Component?node-id=14%3A2&t=JQODmZXm0gX1HmJr-1).

**Comment by AnaBeatrizPontes** [comment]
> @LeoSilvaGomes ,thanks for the feedback. Here's the updated [version](https://www.figma.com/file/btzYmKVvdFS59xTDfCaRZ1/Loading-Component?node-id=14%3A2&t=JQODmZXm0gX1HmJr-1).

I think the uploaded version is better but still not smoothier for the atlas front. Maybe we can try to smooth the component by decreasing the white part or maybe even removing it since the map will only turn green when loading and consequently the loading component will disappear so this will not disturb the loading component visualization. 

@LeoSilvaGomes what do you think?

**Comment by LucasGlopes** [comment]
Thanks again for the feedbacks, @LeoSilvaGomes  and @AnaBeatrizPontes .Based on the tips and examples you provided and studying the React Material UI Library ([Circular Progress Component](https://mui.com/material-ui/react-progress/)), I came up with [three more examples](https://www.figma.com/file/btzYmKVvdFS59xTDfCaRZ1/Loading-Component?node-id=47%3A2&t=yEkHyJsyTm5lRFTw-1) that could work for the atlas front.

**Comment by AnaBeatrizPontes** [comment]
I think the second one is perfect to. Nice job 😄

**Comment by LucasGlopes** [comment]
Thanks, guys. I'll move forward with the second one, then.
