### ISSUE TITLE
Definir variáveis econômicas e demográficas do Geoses

### ISSUE THREAD

**Issue by LeoSilvaGomes** [gpmc-lab-ufrgs/atlas#5]

**Comment by Alinaflores** [comment]
@LeoSilvaGomes fiz abaixo a classificação das variáveis do GeoSES em econômicas **(E)** e demográficas **(D)**:

**(D)** OBSERVED | Número de mortes observadas por causas evitáveis de 5 a 74 anos (2013 a 2017)
**(D)** EXPECTED | número de mortes esperadas para a distribuição da população de acordo com sexo e grupos de idade
**(D)** RR_PREV | risco relativo de mortalidade por causas evitáveis de 5 a 74 anos por padronização indireta por sexo e idade
**(D)** HDI | Índice de Desenvolvimento Humano calculado por município
**(D)** HDI_educ | Índice de Desenvolvimento Humano, dimensão educacional
**(D)** HDI_long | Índice de Desenvolvimento Humano, dimensão da longevidade
?**(D)** HDI_inc | Índice de Desenvolvimento Humano, dimensão de renda
**(D)** GeoSESed | Dimensão de educação (%)
**(E)** GeoSESpv | Dimensão da pobreza (%)
**(E)** GeoSESdp | Dimensão de privação (%)
**(E)** GeoSESwl | Dimensão de riqueza (%)
**(E)** GeoSESin | Dimensão da renda (em reais; 1 dólar americano = 1,76 reais em 2010)
?**(E)** GeoSESsg | Dimensão de segregação por raça e renda (Índice de Concentração nos Extremos, variando de -1 a +1)

Coloquei na frente um "?" na frente da classificação que fiquei na dúvida. Vou falar com o Brei no slack. 
Deixei o índice GeoSES (socioeconômico) de fora dessa classificação, já que ele será o principal indicador do Atlas no momento.

**Comment by LeoSilvaGomes** [comment]
@Alinaflores precisamos de um resumo dessas definições, acredito que elas ficaram muito grandes, se você fazer isso seria incrivel

**Comment by Alinaflores** [comment]
@LeoSilvaGomes eu organizei as 14 variáveis no seguinte formato:
1ª linha: informações que a gente já conhece
2ª linha: definição da variável em PORTUGUÊS
3ª linha: definição da variável em INGLÊS **(já coloquei em negrito, porque é a informação que te interessa agora)**

OBSERVED | Número de mortes observadas por causas evitáveis de 5 a 74 anos (2013 a 2017)
português | Número de mortes observadas por causas evitáveis
**inglês | Observed number of deaths from preventable causes**

EXPECTED | Número de mortes esperadas para a distribuição da população de acordo com sexo e grupos de idade
português | Número de mortes esperadas
**inglês | Expected number of deaths**

RR_PREV | Risco relativo de mortalidade por causas evitáveis de 5 a 74 anos por padronização indireta por sexo e idade
português | Risco relativo de mortalidade por causas evitáveis
**inglês | Relative risk of mortality from preventable causes**

HDI | Índice de Desenvolvimento Humano calculado por   município
português | Índice de Desenvolvimento Humano por município
**inglês | Human Development Index by municipality**

HDI_educ | Índice de Desenvolvimento Humano, dimensão   educacional
português | Índice de Desenvolvimento Humano, dimensão educacional
**inglês | Human Development Index, educational dimension**

HDI_long | Índice de Desenvolvimento Humano, dimensão da   longevidade
português | Índice de Desenvolvimento Humano, dimensão longevidade
**inglês | Human Development Index, longevity dimension**

HDI_inc | Índice de Desenvolvimento Humano, dimensão de renda
português | Índice de Desenvolvimento Humano, dimensão de renda
**inglês | Human Development Index, income dimension**

GeoSES | Índice socioeconômico proposto, variando de -1 a +1   (das piores às melhores condições)
português | Índice socioeconômico
**inglês | Socioeconomic Index**

GeoSESed | Dimensão de educação (%)
português | Dimensão de educação
**inglês | Education dimension**

GeoSESpv | Dimensão da pobreza (%)
português | Dimensão da pobreza
**inglês | Poverty dimension**

GeoSESdp | Dimensão de privação (%)
português | Dimensão de privação
**inglês | Deprivation dimension**

GeoSESwl | Dimensão de riqueza (%)
português | Dimensão de riqueza
**inglês | Wealth dimension**

GeoSESin | Dimensão da renda (em reais; 1 dólar americano = 1,76   reais em 2010)
português | Dimensão da renda
**inglês | Income dimension**

GeoSESsg | Dimensão de segregação por raça e renda (Índice de   Concentração nos Extremos, variando de -1 a +1)
português | Dimensão de segregação por raça e renda
**inglês | Segregation by race and income dimention**

**Comment by Alinaflores** [comment]
About this submission, please, ignore the variable "Human Development Index by municipality", column name "HDI".

**Comment by Alinaflores** [comment]
Link to the dataset at Dropbox folder: https://www.dropbox.com/s/j0y5wsi896joib0/GeoSES_BR.xlsx?dl=0
